title: Empirical Cycling Podcast Transcripts
description: test description
repository: lucasvance/empirical-cycling-transcripts
url: https://github.com/lucasvance
# Custom CSS
sass:
  load_paths:
    - _sass
    - assets/css